name: ci-test

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simpleBank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.1
        id: go
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install migrate
        run: |
          wget https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz
          tar -zxvf migrate.linux-amd64.tar.gz
          mv migrate.linux-amd64/migrate /usr/local/bin/
          rm -rf migrate.linux-amd64 migrate.linux-amd64.tar.gz
      
      - name: Run migration
        run: make migrateup
      - name: Test
        run: make testdb